dataset:
  batch_size: 100
  corpus:
    dev_path: en_ewt-ud-dev.conllu
    name: en_ewt-ud
    root: example/data/en_ewt-ud/
    test_path: en_ewt-ud-test.conllu
    train_path: en_ewt-ud-train.conllu
  dataset_size: 40000
  embeddings:
    dev_path: en_ewt-ud-dev.bert-base-layers.hdf5
    embedding_dim: 768
    root: example/data/en_ewt-ud/
    test_path: en_ewt-ud-test.bert-base-layers.hdf5
    train_path: en_ewt-ud-train.bert-base-layers.hdf5
    type: token
  observation_fieldnames:
  - index
  - sentence
  - lemma_sentence
  - upos_sentence
  - xpos_sentence
  - morph
  - head_indices
  - governance_relations
  - secondary_relations
  - extra_info
  - embeddings
  sub_dim:
    dim_file: all_dim_bert_base.tsv
    dim_num: 20
    do_sub_dim: true
model:
  hidden_dim: 20
  model_layer: 1
  model_type: BERT-disk
  use_disk: true
probe:
  diagonal: False
  dropout: 0
  hidden_layers: 1
  maximum_rank: 1000
  misc:
    corrupted_token_percent: 0.0
    rand_label_condition_length: 1
  params_path: predictor.params
  probe_spec:
    probe_type: MLP
    probe_hidden_layers: 1
  psd_parameters: true
  task_name: corrupted-edge-labels
  task_signature: word_pair_label
probe_training:
  epochs: 60
  loss: cross-entropy
  weight_decay: 0.0
reporting:
  observation_paths:
    dev_path: dev.observations
    test_path: test.observations
    train_path: train.observations
  prediction_paths:
    dev_path: dev.predictions
    test_path: test.predictions
    train_path: train.predictions
  reporting_methods:
  - uas
  root: ./results
