python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-700.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-600.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-500.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-400.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-300.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-200.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-100.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted0-rank1000-1hid-BERT-base-1-SA-50.yaml

python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-700.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-600.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-500.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-400.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-300.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-200.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-100.yaml
python control-tasks/run_experiment.py  SA-config/en_ewt-pos-corrupted1-rank1000-1hid-BERT-base-1-SA-50.yaml
