python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-768-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-400-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-300-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-200-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-150-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-125-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-100-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-90-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-80-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-70-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-60-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-50-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-40-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-30-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-20-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-18-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-16-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-14-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-12-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-10-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-9-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-8-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-7-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-6-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-5-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-4-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-3-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-2-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-1-corr-average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-768-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-400-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-300-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-200-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-150-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-125-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-100-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-90-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-80-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-70-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-60-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-50-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-40-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-30-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-20-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-18-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-16-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-14-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-12-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-10-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-9-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-8-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-7-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-6-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-5-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-4-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-3-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-2-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-1-corr-weighted_average.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-768-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-400-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-300-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-200-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-150-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-125-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-100-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-90-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-80-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-70-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-60-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-50-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-40-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-30-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-20-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-18-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-16-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-14-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-12-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-10-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-9-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-8-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-7-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-6-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-5-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-4-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-3-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-2-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-1-corr-max.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-768-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-400-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-300-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-200-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-150-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-125-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-100-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-90-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-80-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-70-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-60-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-50-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-40-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-30-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-20-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-18-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-16-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-14-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-12-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-10-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-9-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-8-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-7-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-6-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-5-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-4-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-3-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-2-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted0-rank50-1hid-BERT-base-layer-3-SA-1-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-768-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-400-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-300-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-200-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-150-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-125-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-100-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-90-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-80-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-70-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-60-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-50-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-40-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-30-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-20-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-18-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-16-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-14-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-12-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-10-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-9-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-8-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-7-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-6-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-5-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-4-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-3-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-2-corr-random.yaml
python control-tasks/run_experiment.py SA-config/en_ewt-pos-corrupted1-rank50-1hid-BERT-base-layer-3-SA-1-corr-random.yaml
